### ISSUE TITLE
Initialize Git LFS

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/eclipse-tractusx.github.io.largefiles#1]
This repository should host videos and similar files to be used on the [project website](https://eclipse-tractusx.github.io/).
We want to use Git LFS for that reason, which has to be initialized.
There is a [guide](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage) provided by GitHub on how to enable it. 
It also has to be documented (best in the `README.md`), what people need to do, in order to store their files in Git LFS

**Comment by Siegfriedk** [comment]
Pushed files through git lfs. No specific initaliziation was necessary or i had the permissions to do so (but i didn't see any indication)
