### ISSUE TITLE
Not able to push files to the repository from forked repo

### ISSUE THREAD

**Issue by manojava-gk** [eclipse-tractusx/eclipse-tractusx.github.io.largefiles#4]
I have configured git lfs in my local,  but not able to push as I have not write access to the root repository and repo network does not has Git LFS objects already.

# **Steps**

### Using homebrew

```brew install git-lfs```

### Verify that the installation was successful

```git lfs install```

```> Git LFS initialized.```

If you don't see a message indicating that git lfs install was successful, please contact [GitHub Support](https://support.github.com/request?tags=docs-generic). Be sure to include the name of your operating system.

## Configure GIT LFS

Open Terminal.

Change your current working directory to an existing repository you'd like to use with Git LFS.

To associate a file type in your repository with Git LFS, enter git lfs track followed by the name of the file extension you want to automatically upload to Git LFS.

For example, to associate a .psd file, enter the following command:

```git lfs track "*.zip"```

```> Adding path *.zip```

Every file type you want to associate with Git LFS will need to be added with git lfs track. This command amends your repository's .gitattributes file and associates large files with Git LFS.

Add a file to the repository matching the extension you've associated:

```git add <path>```

Commit the file and push it to GitHub:

```git commit -m "add file .zip"```

```git push```

**Comment by Siegfriedk** [comment]
I have pushed all quality kit zip files @maximilianong mentioned to me. This should also now allow *.zip files to be tracked through lfs.

Please verify @manojava-gk

**Comment by Siegfriedk** [comment]
pls reopen if still an issue @manojava-gk & @maximilianong
